// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCARnQXdpihalKFSfNeQ1QZY6jDOs_H6fs',
    appId: '1:1049388490916:web:d991c7e8a57474fbee4631',
    messagingSenderId: '1049388490916',
    projectId: 'today-i-b7873',
    authDomain: 'today-i-b7873.firebaseapp.com',
    storageBucket: 'today-i-b7873.appspot.com',
    measurementId: 'G-3ZXXZF4LHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvaHlk5ljI9fbspl7e9vWxkpvepfcAwM',
    appId: '1:1049388490916:android:20c04ae8e0ac47ecee4631',
    messagingSenderId: '1049388490916',
    projectId: 'today-i-b7873',
    storageBucket: 'today-i-b7873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXN7cuZVND8Z8J8Ve2Cf2cGC3t2zT3Lgs',
    appId: '1:1049388490916:ios:0f6be7d0fedda735ee4631',
    messagingSenderId: '1049388490916',
    projectId: 'today-i-b7873',
    storageBucket: 'today-i-b7873.appspot.com',
    iosClientId: '1049388490916-a5ess8saaakeego1cgrdgtc0ejilneiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todayi',
  );
}
